databases:
  - name: sports-matching-app-db
    databaseName: ports-matching-app-db
    user: sports-matching-app-user
    region: singapore
    plan: free

services:
  - type: web
    name: sports-matching-app
    env: python
    region: singapore
    plan: free
    branch: main
    healthCheckPath: /
    buildCommand: './build.sh'
    startCommand: 'gunicorn config.wsgi --log-file -'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sports-matching-app-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4


    autoDeploy: true