# Generated by Django 5.0.6 on 2024-05-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='sample_1',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_10',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_2',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_4',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_5',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_6',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_7',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_8',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_9',
        ),
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='試合場所'),
        ),
        migrations.AddField(
            model_name='item',
            name='team',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='チーム名'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sample_3',
            field=models.IntegerField(blank=True, null=True, verbose_name='チームレベル'),
        ),
    ]
