# Generated by Django 5.0.6 on 2024-05-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_item_day_item_hour_item_min_item_month_item_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='hour',
            field=models.IntegerField(blank=True, choices=[(0, '0時'), (1, '1時'), (2, '2時'), (3, '3時'), (4, '4時'), (5, '5時'), (6, '6時'), (7, '7時'), (8, '8時'), (9, '9時'), (10, '10時'), (11, '11時'), (12, '12時'), (13, '13時'), (14, '14時'), (15, '15時'), (16, '16時'), (17, '17時'), (18, '18時'), (19, '19時'), (20, '20時'), (21, '21時'), (22, '22時'), (23, '23時'), (24, '24時')], null=True, verbose_name='時間'),
        ),
    ]
