# Generated by Django 5.0.6 on 2024-05-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_item_hour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='sample_3',
            new_name='level',
        ),
        migrations.AddField(
            model_name='item',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='一言'),
        ),
        migrations.AddField(
            model_name='item',
            name='sports',
            field=models.IntegerField(blank=True, choices=[(1, '軟式野球'), (2, '硬式野球'), (3, 'サッカー'), (4, 'バスケットボール')], null=True, verbose_name='sports'),
        ),
    ]
